---
use_resolved: true
use_networkd: true
use_timesyncd: true

locale_default:
  LANG: 'en_US.UTF-8'

systemd_conf_default: {}
systemd_conf_role: {}

journald_conf_default: {}
journald_conf_role: {}

logind_conf_default: {}
logind_conf_role: {}

resolved_conf_default: {}
resolved_conf_role: {}

timesyncd_conf_default: {}
timesyncd_conf_role: {}

dnf_conf_default: {}
dnf_conf_role: {}

dnf_makecache: false

dnf_packages_default:
  'glibc-langpack-en': present
  'initscripts': present
  'hostname': present
  'dnf': present
  'passwd': present
  'vim-enhanced': present
  'dnf-command(leaves)': present
  'python-unversioned-command': present
dnf_packages_role: {}

sudo_group: 'wheel'

# vim: set ts=2 sw=2 et:
