---
- name: restart resolved
  systemd:
    name: systemd-resolved.service
    state: restarted
  when: not chroot

- name: restart timesyncd
  systemd:
    name: systemd-timesyncd.service
    state: restarted
  when: not chroot

- name: restart homed
  systemd:
    name: systemd-homed.service
    state: restarted
  when: not chroot

# vim: set ts=2 sw=2 et:
