---
- name: knielsen
  user:
    comment: 'Kristian Nielsen'
    name: knielsen
    shell: '/bin/bash'
    uid: 1004
    group: users
    groups:
    - '{{ sudo_group }}'

- name: knielsen - authorized_keys
  authorized_key:
    user: knielsen
    key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKUAYFshLA2BvcTrKjW90lDjIQkCJ16+uIjfKqB0HDk/ knielsen@urd'

# vim: set ts=2 sw=2 et:
