---
userdata:
  'esmil':
    name: 'Emil Renner Berthing'
    uid: 2000
    tasks: true
    password: '$6$1RwgF85UfHCIPzNd$Ow9pn9muQ2raoB0andBcrDkB9UqqmXylqWVXDsxgFqhHc5uNk7MZdhtGnz9P5UOSwadEpHkSG0VrP9eOPM8nj0'
    authorized_keys:
    - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOuodYrzc+xUF8BiC39KfzeK11BFXmz6rYMEHxYfhjum esmil@stitch'
    - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIESZrJ5ystrdDYZok0jCJKePa2JUL+t2DrbkMWwNheeQ esmil@plastik2'
    - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINGvUI9Gme812b75R//zEGJm5pURhaJpWCn7lwMuOrVC esmil@alcazar'
    - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHo3wq70/mMiOTgNdijxDp7CjrclMOM9f7JSnMtqSevM esmil@matahari'
    - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICafi2jClWwIGo/iU32wJFGAINKKuCfID5uWk+brl4Lo esmil@hercules'

  'ast':
    name: 'Asbjørn Sloth Tønnesen'
    uid: 2001
    authorized_keys:
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAyLX2AICoAhOSOnZth9PMlxqgPrw//J2wMtcHQUppqSjHGFkxIkOWnMUwbSZo/kFj2J8e8GJ7xwmC3tTblmJl+Ba1R77SEETJQpM1/TgWcCK5L7KpK/XP7yTCPMds1vczjgIIMA+DS9iuNQkqLSA5B6gdGfbfuPsMB/W8L2gqkVFMiE3zcrxGLwaPPW7fo9rA2Z7tMEZMFy9SB0u3mqY5aoBiI9P5U3rgn96SO8cs/JVnf99RfkJQWmBamZIH3vqwvC3uG+QgB0cQ9Sy9/I4Q75YQKnGPS+ySQVvo3nY9KpULAbHoVZyu3CtzDfXYOxgUXhJ/GerZZUbyHkrndhXteQ== asbjorn@asbjorn.it'

  'flummer':
    name: 'Thomas Flummer'
    uid: 2002
    authorized_keys:
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA0QPLM0CyCr5tqdIeftC4kgmoGOE0EvOoZOZXrJqx2lRJfOh+eK/IjQv3K/MyqPhcHc6swcTfv5LpdgmxxhJmruXTX9OnDp5kyuoYknvD601WwfZATK7tqH3t9okIoW0qobb1jjciCkcNo0mtJ+BJ2HvoELAB0BASQy7EliLuFV6SImWV5nZ5kGaAs8lzS/Wl1c3FJT9OKaHgyYgkHMjH2FuFmQJQ1g+NKBx9BU7XQCddxY5U/s5EO5R6e2tZjxdeRu0v4k5FtUjryaj0zLh6JQteDNQpMr+4JKyfoT2b3TjJSNkd1k338V49CjZkCnt8qi+q4ahyzJVT0aCxSHT4+w== tf@labitat.dk'

  'riiiis':
    name: 'Christian Riis'
    uid: 2003
    authorized_keys:
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDA/44Ucz9o402vT+aqlQGM37cIagF+lo7tVEvSbksuNC1DgUCTXHzhLG3STx2SdTbL+toGe9p7z/lW5xysPcS01heFt+XzbJbEVTHfXmng0NgIxZPactgJJ0ulCoGe+ehefnVgTFnidTxkm1MngeJbYqlNP5nf6RgygB+yM4P4GGtl2Sa/D/oWuQB7CIvtRrLGl96ON31AwWfVmXRsNT/rqmuMmqvJpR+ZaONfbN3JVYu7J1aHpkIRAN+5LsaSueZTTrmIxI3oGzuIrqegjsf9DxeVnjg6ZppKFSrWKMTx90Ao+Whea7UyXSiAcPl+UEWuE8zf1yVr0V4IxC+TDwuB riiiis@KosmoHP'
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOl1iI6dXybz5OhwXFim8FW+KGCGY1Nyx8QMTQjoX1fU0SrBgD8UElq8TbnZjVwrjv1qu53HhHJlZDWr5LGoi9SbBhHEq+zTWzLQwBlUdTv9fkLRTcOENKRM7Y71U/bhPzoIJPF6CBln8X+0Ymvzc8JHh3CP9bJiIxk4cBkgxwL6j6q2Laf+rVLUwdEGN4+T6OsGXIVyF8+pCwa2XmgRf+WVuUj8PAB4SnMYcbH3bOd+twG1CIU89RqLRAxKEGaS9vsuUAHtXxfkyrYyxSeVw0HcyjCom+/K/S5VtdomkgMHTDZ6S6Ua+nlu8x6tY6K83Zgnq/GJZ0TxcA4PCRkwtR riiiis@3k3'

  'knielsen':
    name: 'Kristian Nielsen'
    uid: 2004
    authorized_keys:
    - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKUAYFshLA2BvcTrKjW90lDjIQkCJ16+uIjfKqB0HDk/ knielsen@urd'

  'k2OS':
    name: 'René Mikkelsen'
    uid: 2005
    authorized_keys:
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAqmvJAMyY117n638/rYw6EtDSY+iHG5xbg/pO932T/0D9X1MVmEnQyOa3597ufBSTUs1GdKtG2N0lyRq91OBS9JN4E+4Hm1t3UgH7/EKbun1Qb0HQMKsI4AR1onsFBeSCkZiijbg9lf7SL6+Ea0cYoXqy3uCWj/Q1PXq+3WlnlLnl9tFhytwuInuTmQvYpHwGgiEs1hIJWjBCbLPMyWbU7LOE6VzXQTbXCJz8FuraX5noiubpii74nHtUzM466ED3JUnf3TPWG8uGitJ7bT2/ZOQ5W83wUC0Xc80Gai3ilRXapQReE7oybePyXkVhP5odBiCu36iqyEgGol8Sb6+S7Q== rene@gw'
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC46lbGFV/7kM4w1C1dLfnIAAanX+IV9vDHw3D8uzEGmwWV0XL8e5rdv1RpKZKHpkAgBcD1m2Y1jVDj1R8QdbGZNSDUoP8z3dMemBDJkqunJjTPIPPeyQFprk/hVkJ4pK0Y+w1lKJquIVDkhQYIQCzuxZraAAq4AgVT3L5ft9WuJm3Apk1w+GESK0oQCZNDOhT8MblqiR+JZBUo2gd68jxr9+Wq3ekE7I/N3sO9HFeze4axcTQKcTs39Oi+RYNKJh44sAdxeo2HUX0IYasyxEr2z8H3BmMn1R/Fxwzj2seLYFu1U21UDZdqN+AfgpEabox0HOKvrNDNBGTC5KwWgWBB rene@denada.dk'

  'richard':
    name: 'Richard Graham'
    uid: 2006
    authorized_keys:
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC3qClonWiTr9cP7t6jAburDU33d4zZ7mgIVvJ6dNb1DCwBzA6pGZ4UPL85t7C1MWRBeNMTSOvqbrX+KKSRMH5ScF1Fx/GUzPivzhvweD7lq+JjAP4igzU0t+LKHVc7yNySAjfUikoNqD84XkELpoNVaRHZBtoZVbHswUyRtjj0WUT7a+fQ6z4YwnX+DnTgW5tc3M+GSeR8viIZWahPeYHVDTNE9xTOPvTALjtICTGtaunlYV4VeICUunej5r90xfzwT/wzJVFrgKeTVDRB40pCc0EG54pV6odhZJx8fk9HAS3XDRGJevzx7rzNtqclkmW1o1s2rjbSKukzN2K2XQ4XGNm4vDChR+Z7jgxcg9VgViDeyv1ji8d+xUC+lFlLzDimND7hdyY2UDJdXutVMp6L0ibhlPZjnH9OIY+iEmvipCOOnfiA8wqhYtAUlDYiWVcqIP1DgOFMOcoduKnh3KBnpCc8hcmOilgA33B2qLwpgFqkP/D9vZwhvN/7C4rH66s= richard@richard-T430s'

  'max':
    name: 'Max Campbell'
    uid: 2007
    authorized_keys:
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDtbHB0B+IEPtC5ni2A9wGGehq21euv46cpowXlucXpe8Q+n3hILAJ2Ce5qvYFTDbpK72gifhXtq5xaG4ZXZJy/QYaKO00mS/Xq50WegqA9bZ9u4Ddw3XAHOyc1QYyoa5edGrbb46/PC861G5KdQgNc4PHf6iTQWYdD/0FAx4B7sqMYC4IMjFmlZWWgzKBOQG+LQ3CZ7UVj70X2YU5l31crJaCPS9za3m/Q5XH+2pYp5q5ixzfU7RVa1AqYwiCJDFsaQ5wxDsLCvy5IxOLsV3NW7iElnvTU+sBavRi3CEi5CH22eBbOj/HPsKnuxQomnOJRa4epM6YR3NfsWshBJo0x max@max-Laptop'

  'semi':
    name: 'Troels Bang Jensen'
    uid: 2010
    authorized_keys:
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDUqzAFehYCGZNUZkpARApPI4P/RjrL3qS8KniOyZOpL2YLE7WzzQWoLFhlmuKPygWqHBSPkZNm6JMi36fI5NurIk9GkLw8RnWhcqlA1miaD2wC3iQ2hoFOko2artgM7urZ2HCO0ILfjNzMdWvdBnQQWHudzUvPFNKmOuagp6GvEbs0X7kXi3X1+8lfCkRe0H6i4/RuHakUGQ9xipiIR5SoYdpnwHWlJp3trEM4WQtmQcxFkZZbW0yrujo2iqZ3MwWBkfA9PZG9BuooAWGZzUt/NxF5ImZISyaKG/DTlsEe+cEvjRmLYXZHKcgngC3zsQZAfoNjGXqlbsXbjont1u5p marvin@merlin'

  'graffen':
    name: 'Jesper Hess Nielsen'
    uid: 2011
    authorized_keys:
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCbxFVukt5TIzoB0HX2q8b8lHJmXD1juzsWOu5XkexVDlCsvupa1cZ/OVkrIEAbDKk6RmJQj0TJ2O5+v9hbf0TDi0Pi+V8ADZIgO+OW5a4EeXsU72a4CN0nEocQhUPfQuC4IU+F7icoG2/I9jXg7U6p1LhBr8vlC3cNHnrH3yqrakrUR51/iRVIwo4FKvQg7jutaKTyOjlYa1uTdaczvAzNHWEdytCQgFnkzpR9fHvzkA79qHUD9n32rIpJicRJsHY3NnyDGfBcDv+4sLq15sM9jN83duGnSuMMtZgfSriwMUd/UwVReU2ZKxjMLe3WHB7+ZE/p39OJk/gjVfWJVh/za1/teTAwaLLmxh/HFt+AVYWkCj22fUxscl0dh2zy6Ki1Ua3ApChn6v6Gvng6khobFlxawSJZ49+0KoAl1qqFMR1o9EGWvqgDPuITAqJFN+ik0jxcxfmKrG3mbOYM1ikhJd0ER8wbS8e6NowHUBV7PUyDqxP5VM2gum58IYrDqaP2RYYi9vWWnXJJA8J1t+Wp3bF7fdktyVgkd7HQk02uVkxdMQQ802GCrQQuvJhWTCzrgkgrjPY8p0KcbCNt6jYQOUKV0T2vp6PbTJ5XWKb5u7gVXW1xiP9dYzgAr0DroiTK4xIuF80mv1Rfst0ceHAIQVcQ3GcGbh000QUYzbHT2Q== openpgp:0x265EE03C (Graffen)'

  'hafnium':
    name: 'Emil Petersen'
    uid: 2012
    authorized_keys:
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCyPMNUFzX7uYqyAMsRj9CDT6L6ek2KOw/X2xYXgQs0DYBl/oOVeMJodHZ4Bt8VA2jIPpykh+kzaPli5D+lJwznavdvTcusYIURHHDc7LeZ9aWRlRjlH2UTpQSCsZRWueDHXSL4UcniBTfe+BoX6g5VNWvnyd1RI9bS2IUTU7sT2tqnJY6zUO//1phHkOx0XKXdCfbih2f2+VNA14GN3gWVKUIe5Tzy4X/ZnsWOOuysTesscfuQsr0wMTbxHV68WFIvMPo7H0jA6nOiU6r55A8wASbhvdmumySIw4frW5upE+YfwLz7n8oxhCf5LuZ4iJuXC6EtBpAv0BuD7vpweW+7RPEQ+I3Y44BGdb7OAOSgHOOETpHwskSYiGkchANV03ERBMIhzycupSCPY4Er9AjeSp+/l0IPM0bEfRtvnCMDOLKZxGmtC246NTkQJuCJ5FLp9YXRBjmG7PPSXkMFTGRt5PkZu/+v8+7JH5+2rREbFLaznJzpw75VOCcvnWNvXaInl7ZpZePmbhqpvFGS0rJeJ4t+IwlpzDj9d3LQoBN9MCkKajR7j70TOlg89H1zTzR0kadQx5EMZgLDVt6dLQzbiGfw2LCNHGpgW9UBhsCEq9LwNvHIX62Fv9sqGsJnkCjBkyPTlQZxBqRBh4YIx2V7rxXJCSPiYHctNT3ewMdIew== haf@hafnium.me'

  'signout':
    name: 'Dennis K Jensen'
    uid: 2024
    authorized_keys:
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCZQFV1lnkbpxGLb8vzatymPoQBQ8J8CRBdBV4IvmMevGTWBAlOvlr9tIKntkl+GS7lP71i7df7EGD2Oiwgv+3L+gdyTmReo9gl8h2z/uh1AUtL27PK6BMP7SXzv7tqQbO69saSBpljCbuiYWbO6T1lOT6KQMRUkqDfIUYHsK+IktXvvaFWJfRrCZ2B98lg18srWcz1AO4GJjoZtzNhy2KUFnQsp3gPCRdXI1PJMVuvhL997aa2vaCXhPPIIwXh8HhmV3mlNCx6oP1cNoMzsymloKqvX0v3hbsp+kPQXRLIt7d5sxjgb2C3E9DVNAOPHO4CJA9G24IFEq2/ZMvNO/3c56ZROW/KuIDFeUez1iJ8uu81TtQ0TU3t+35LOIyv47jkt6zjaj3CciAZGiJHvafyblSWk7+UDRSzkwtyc2X+XIWQG0LSKxhsXYB3FHMSqmMuRJViN/kAVIkCJU0WuEdhZqswjzfSgR9COoroGQGsbM7kXCk+U7ekXcxNP5ttgv8p4qamS9u6w8WIMvLJK5cOU4OIVtsPsFmk2ot6zQYEQTnRCiqscsPMLLFsapnvydLJ8TtDjhWtFzQ4tD8XkN9+/fxd8G45qk8R921Y7Ftb6qhphIXW/vCH6n/+hN920nj1S/AnWiVPTrBW0tRlI6sUfLkJKyI+Nld/yBPwb+PMmw== foldefrugt'
    - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHeDUHoziX3gx9hJMSh7MComcrGWi6ZV+ZKf/iFNPYiB signout@ripperen'

  'rasmis': {}

  'jobbe': {}

  'allover':
    name: 'Oliver Allover'
    uid: 2025
    authorized_keys:
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDErwnvNA9FhRsZqd7lFmfvQmWCvCRu6OmyOUw2WZIcjY11h/dBGOZYT4PHG42IChFcFd/RczCArC3B3Li9cI+TaNNBlVxyElZsg2L+98KeGzapPx02e/bgea9Vf1DKsC5DIhDg1ZRp5BcsY9w4l53b12EPWDTzAr87bvlowoQE8DKzkOmLi3RhFqJrCY5CJOzde5RaRbAaJby+SmqVnauS0j8PgZP3QJF4cpnbVg3gdlCB4neSyeh7btKe6X3nu4ySZuUBKDc8zipd2aJX+5xJGmMcqF/ybJxNY3yzEV+Xt/nCBHwa/X78gl3QsaV6xJfqYaUiITjGj6lXKCGi3zvabKIGV/THfFR548vBqLkzRfnUkUAXdjMyx1Aqm7U6d2hpm4cboBpz2+h6troKD38MVCCcIrdEpBUZzxxK1tCYImXO1FowTmH6qWo9/3h5t+bJEZQWp0vR73ZW01exrAseSlFGT1a1vw3PRo1lspSn/B4SuziYYnwPbCpR9ZviOw8= allover@labitat'

users: {}

# vim: set ts=2 sw=2 et:
