---
- name: Install avahi, tools and nss-mdns
  dnf:
    name:
    - avahi-tools # pulls in avahi package
    - nss-mdns
    state: present
  tags:
  - packages

- name: Configure avahi-daemon
  ini_file:
    path: '/etc/avahi/avahi-daemon.conf'
    no_extra_spaces: yes
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
  - section: server
    option: 'host-name'
    value: '{{ hostname }}'
  - section: server
    option: 'domain-name'
    value: 'local'
  - section: server
    option: 'browse-domains'
    value: ''
  - section: server
    option: 'use-ipv4'
    value: 'yes'
  - section: server
    option: 'use-ipv6'
    value: 'yes'
  - section: server
    option: 'allow-interfaces'
    value: 'lan11,lan12,lan14'
  - section: server
    option: 'enable-dbus'
    value: 'yes'
  - section: server
    option: 'disallow-other-stacks'
    value: 'yes'
  - section: wide-area
    option: 'enable-wide-area'
    value: 'yes'
  - section: publish
    option: 'disable-publishing'
    value: 'no'
  - section: publish
    option: 'disable-user-service-publishing'
    value: 'no'
  - section: publish
    option: 'publish-addresses'
    value: 'yes'
  - section: publish
    option: 'publish-hinfo'
    value: 'yes'
  - section: publish
    option: 'publish-workstation'
    value: 'no'
  - section: publish
    option: 'publish-domain'
    value: 'yes'
  - section: publish
    option: 'publish-dns-servers'
    value: '185.38.175.0,2a01:4262:1ab::'
  - section: publish
    option: 'publish-resolv-conf-dns-servers'
    value: 'no'
  - section: reflector
    option: 'enable-reflector'
    value: 'yes'
  notify:
  - restart avahi-daemon

- name: Configure hosts
  template:
    dest: '/etc/avahi/hosts'
    src: avahi-hosts.j2
    owner: root
    group: root
    mode: 0644
  notify:
  - restart avahi-daemon

- name: Enable avahi-daemon service
  systemd:
    name: avahi-daemon.service
    enabled: yes
    masked: no
    state: started
  when: not chroot
- name: '- when in chroot'
  command: systemctl enable avahi-daemon.service
  args:
    creates: '/etc/systemd/system/multi-user.target.wants/avahi-daemon.service'
  when: chroot

- name: Use nss-mdns
  lineinfile:
    path: '/etc/nsswitch.conf'
    regexp: '^hosts:'
    line: 'hosts:      files mdns_minimal [NOTFOUND=return] dns myhostname'

# vim: set ts=2 sw=2 et:
