---
- name: Make sure /etc/kernel/install.d exists
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - '/etc/kernel'
    - '/etc/kernel/install.d'

- name: Mask grubby
  file:
    path: '/etc/kernel/install.d/20-grubby.install'
    src: '/dev/null'
    state: link

- name: Create syslinux loader entry and menu
  copy:
    dest: '/etc/kernel/install.d/'
    src: '{{ item }}'
    owner: root
    group: root
    mode: 0755
  with_fileglob: 'kernel/*.install'

- name: Set kernel command line
  template:
    dest: '/etc/kernel/cmdline'
    src: cmdline.j2
    owner: root
    group: root
    mode: 0644

- name: Install kernel
  dnf:
    name: kernel
    state: present
  tags:
    - packages

# vim: set ts=2 sw=2 et:
